/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edgarmayorga.principal;

import com.edgarmayorga.metodocostominimo.gui.Pnl_Costo_Minimo;
import com.edgarmayorga.metodoesquinanoroeste.gui.Pnl_Esquina_Noroeste;
import com.edgarmayorga.metodografico.gui.Pnl_Metodo_Grafico;
import com.edgarmayorga.metodosimplex_dual.gui.Dlg_Parametros;
import com.edgarmayorga.metodosimplex_dual.gui.Pnl_Metodo_Simplex_Dual;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author DellMayorga
 * Este es el formulario principal que contendrá las ventas internas, las cuales cada una pertenece a un 
 * metodo diferente de los que he visto en clase.
 * Este formulario también contiene la barra de menú
 */
public class Frm_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Principal
     * Edgar Alberto Mayorga Jimenez 11/09/2017
     */
    public Frm_Principal() {
        initComponents();
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize().getSize());
        this.setTitle("INVESTIGACION DE OPERACIONES");
        this.setVisible(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpPrincipal = new javax.swing.JDesktopPane();
        ifGrafico = new javax.swing.JInternalFrame();
        ifSimplexDual = new javax.swing.JInternalFrame();
        ifEsquinaNoroeste = new javax.swing.JInternalFrame();
        ifCostoMinimo = new javax.swing.JInternalFrame();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        miSalir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        miGrafico = new javax.swing.JMenuItem();
        miSimplex = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miEsquinaNoroeste = new javax.swing.JMenuItem();
        miCostoMinimo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ifGrafico.setClosable(true);
        ifGrafico.setIconifiable(true);
        ifGrafico.setMaximizable(true);
        ifGrafico.setResizable(true);
        ifGrafico.setTitle("METODO GRAFICO");
        ifGrafico.setMinimumSize(new java.awt.Dimension(500, 500));
        ifGrafico.setPreferredSize(new java.awt.Dimension(500, 500));
        ifGrafico.setVisible(false);

        javax.swing.GroupLayout ifGraficoLayout = new javax.swing.GroupLayout(ifGrafico.getContentPane());
        ifGrafico.getContentPane().setLayout(ifGraficoLayout);
        ifGraficoLayout.setHorizontalGroup(
            ifGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );
        ifGraficoLayout.setVerticalGroup(
            ifGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        dpPrincipal.add(ifGrafico);
        ifGrafico.setBounds(20, 50, 220, 130);

        ifSimplexDual.setClosable(true);
        ifSimplexDual.setIconifiable(true);
        ifSimplexDual.setMaximizable(true);
        ifSimplexDual.setResizable(true);
        ifSimplexDual.setTitle("METODO SIMPLEX / DUAL");
        ifSimplexDual.setMinimumSize(new java.awt.Dimension(500, 500));
        ifSimplexDual.setPreferredSize(new java.awt.Dimension(500, 500));
        ifSimplexDual.setVisible(false);

        javax.swing.GroupLayout ifSimplexDualLayout = new javax.swing.GroupLayout(ifSimplexDual.getContentPane());
        ifSimplexDual.getContentPane().setLayout(ifSimplexDualLayout);
        ifSimplexDualLayout.setHorizontalGroup(
            ifSimplexDualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ifSimplexDualLayout.setVerticalGroup(
            ifSimplexDualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        dpPrincipal.add(ifSimplexDual);
        ifSimplexDual.setBounds(430, 150, 200, 170);

        ifEsquinaNoroeste.setClosable(true);
        ifEsquinaNoroeste.setIconifiable(true);
        ifEsquinaNoroeste.setMaximizable(true);
        ifEsquinaNoroeste.setResizable(true);
        ifEsquinaNoroeste.setTitle("METODO ESQUINA NOROESTE");
        ifEsquinaNoroeste.setMinimumSize(new java.awt.Dimension(500, 500));
        ifEsquinaNoroeste.setPreferredSize(new java.awt.Dimension(500, 500));
        ifEsquinaNoroeste.setVisible(false);

        javax.swing.GroupLayout ifEsquinaNoroesteLayout = new javax.swing.GroupLayout(ifEsquinaNoroeste.getContentPane());
        ifEsquinaNoroeste.getContentPane().setLayout(ifEsquinaNoroesteLayout);
        ifEsquinaNoroesteLayout.setHorizontalGroup(
            ifEsquinaNoroesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ifEsquinaNoroesteLayout.setVerticalGroup(
            ifEsquinaNoroesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        dpPrincipal.add(ifEsquinaNoroeste);
        ifEsquinaNoroeste.setBounds(630, 300, 500, 500);

        ifCostoMinimo.setClosable(true);
        ifCostoMinimo.setIconifiable(true);
        ifCostoMinimo.setMaximizable(true);
        ifCostoMinimo.setResizable(true);
        ifCostoMinimo.setTitle("METODO COSTO MINIMO");
        ifCostoMinimo.setMinimumSize(new java.awt.Dimension(500, 500));
        ifCostoMinimo.setNormalBounds(new java.awt.Rectangle(320, 190, 500, 500));
        ifCostoMinimo.setPreferredSize(new java.awt.Dimension(500, 500));
        ifCostoMinimo.setVisible(false);

        javax.swing.GroupLayout ifCostoMinimoLayout = new javax.swing.GroupLayout(ifCostoMinimo.getContentPane());
        ifCostoMinimo.getContentPane().setLayout(ifCostoMinimoLayout);
        ifCostoMinimoLayout.setHorizontalGroup(
            ifCostoMinimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ifCostoMinimoLayout.setVerticalGroup(
            ifCostoMinimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        dpPrincipal.add(ifCostoMinimo);
        ifCostoMinimo.setBounds(500, 500, 500, 500);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        miSalir.setMnemonic('x');
        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        fileMenu.add(miSalir);

        menuBar.add(fileMenu);

        jMenu1.setText("Metodos");

        jMenu2.setText("Programación lineal");

        miGrafico.setText("Método gráfico");
        miGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGraficoActionPerformed(evt);
            }
        });
        jMenu2.add(miGrafico);

        miSimplex.setText("Método simplex / dual");
        miSimplex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSimplexActionPerformed(evt);
            }
        });
        jMenu2.add(miSimplex);

        jMenu1.add(jMenu2);

        jMenu3.setText("Modelos de transporte");

        miEsquinaNoroeste.setText("Esquina noroeste");
        miEsquinaNoroeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEsquinaNoroesteActionPerformed(evt);
            }
        });
        jMenu3.add(miEsquinaNoroeste);

        miCostoMinimo.setText("Costo mínimo");
        miCostoMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCostoMinimoActionPerformed(evt);
            }
        });
        jMenu3.add(miCostoMinimo);

        jMenu1.add(jMenu3);

        jMenu4.setText("Modelos de asignación");
        jMenu1.add(jMenu4);

        menuBar.add(jMenu1);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miSalirActionPerformed

    private void miGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGraficoActionPerformed
        // TODO add your handling code here:
        try {
            Pnl_Metodo_Grafico mtdGrafico = new Pnl_Metodo_Grafico();
            ifGrafico.setContentPane(mtdGrafico);
            ifGrafico.setMaximum(true);
            ifGrafico.setDefaultCloseOperation(1);
            ifGrafico.setVisible(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miGraficoActionPerformed

    private void miSimplexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSimplexActionPerformed
        // TODO add your handling code here:
        try {
            Pnl_Metodo_Simplex_Dual objSimplexDual = new Pnl_Metodo_Simplex_Dual();
            ifSimplexDual.setContentPane(objSimplexDual);
            ifSimplexDual.setMaximum(true);
            ifSimplexDual.setDefaultCloseOperation(1);
            ifSimplexDual.setVisible(true);
            
            //Dlg_Parametros objParametros = new Dlg_Parametros(this, true);
        } catch(Exception ex) {
            System.out.println("error: " + ex.getStackTrace());
        }
    }//GEN-LAST:event_miSimplexActionPerformed

    private void miEsquinaNoroesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEsquinaNoroesteActionPerformed
        // TODO add your handling code here:
        try {
            Pnl_Esquina_Noroeste objEsquinaNoroeste = new Pnl_Esquina_Noroeste();
            ifEsquinaNoroeste.setContentPane(objEsquinaNoroeste);
            ifEsquinaNoroeste.setMaximum(true);
            ifEsquinaNoroeste.setDefaultCloseOperation(1);
            ifEsquinaNoroeste.setVisible(true);
        } catch(Exception ex) {
            
        }
    }//GEN-LAST:event_miEsquinaNoroesteActionPerformed

    private void miCostoMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCostoMinimoActionPerformed
        // TODO add your handling code here:
        try{
            Pnl_Costo_Minimo objCostoMinimo = new Pnl_Costo_Minimo();
            ifCostoMinimo.setContentPane(objCostoMinimo);
            ifCostoMinimo.setMaximum(true);
            ifCostoMinimo.setDefaultCloseOperation(1);
            ifCostoMinimo.setVisible(true);
        } catch(Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_miCostoMinimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane dpPrincipal;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JInternalFrame ifCostoMinimo;
    private javax.swing.JInternalFrame ifEsquinaNoroeste;
    private javax.swing.JInternalFrame ifGrafico;
    private javax.swing.JInternalFrame ifSimplexDual;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miCostoMinimo;
    private javax.swing.JMenuItem miEsquinaNoroeste;
    private javax.swing.JMenuItem miGrafico;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JMenuItem miSimplex;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
