/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edgarmayorga.metodosimplex_dual.gui;

/**
 *
 * @author DellMayorga
 */
public class Dlg_Parametros extends javax.swing.JDialog {
    private int numero_variables_desicion;
    private int numero_restricciones ;
    private String objetivo_funcion;
    private boolean mostrar_panel = false;

    /**
     * Creates new form NewJDialog
     */
    public Dlg_Parametros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNoVariablesDesicion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNoRestricciones = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbMaxMin = new javax.swing.JComboBox<>();
        btnContinuar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parametrización", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("No. variables desición:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 69, 130, -1));
        jPanel1.add(txtNoVariablesDesicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 69, 100, -1));

        jLabel2.setText("No. de restricciones:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 120, -1));
        jPanel1.add(txtNoRestricciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 109, 100, -1));

        jLabel3.setText("Objetivo función:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 100, -1));

        cbMaxMin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maximizar", "Minimizar" }));
        jPanel1.add(cbMaxMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 149, 100, -1));

        btnContinuar1.setText("Continuar");
        btnContinuar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinuar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 229, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuar1ActionPerformed
        // TODO add your handling code here:
        if(!txtNoVariablesDesicion.getText().trim().equals("") && !txtNoRestricciones.getText().trim().equals("")) {
            setNumero_variables_desicion(Integer.parseInt(txtNoVariablesDesicion.getText().trim()));
            setNumero_restricciones(Integer.parseInt(txtNoRestricciones.getText().trim()));
            setObjetivo_funcion(cbMaxMin.getSelectedItem().toString());
            setMostrar_panel(true);
            this.dispose();
            //this.setDefaultCloseOperation(0);
        }
    }//GEN-LAST:event_btnContinuar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dlg_Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dlg_Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dlg_Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dlg_Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dlg_Parametros dialog = new Dlg_Parametros(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar1;
    private javax.swing.JComboBox<String> cbMaxMin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNoRestricciones;
    private javax.swing.JTextField txtNoVariablesDesicion;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the numero_variables_desicion
     */
    public int getNumero_variables_desicion() {
        return numero_variables_desicion;
    }

    /**
     * @param numero_variables_desicion the numero_variables_desicion to set
     */
    public void setNumero_variables_desicion(int numero_variables_desicion) {
        this.numero_variables_desicion = numero_variables_desicion;
    }

    /**
     * @return the numero_restricciones
     */
    public int getNumero_restricciones() {
        return numero_restricciones;
    }

    /**
     * @param numero_restricciones the numero_restricciones to set
     */
    public void setNumero_restricciones(int numero_restricciones) {
        this.numero_restricciones = numero_restricciones;
    }

    /**
     * @return the objetivo_funcion
     */
    public String getObjetivo_funcion() {
        return objetivo_funcion;
    }

    /**
     * @param objetivo_funcion the objetivo_funcion to set
     */
    public void setObjetivo_funcion(String objetivo_funcion) {
        this.objetivo_funcion = objetivo_funcion;
    }

    /**
     * @return the NoRestricciones
     */
    public javax.swing.JTextField getNoRestricciones() {
        return txtNoRestricciones;
    }

    /**
     * @param NoRestricciones the NoRestricciones to set
     */
    public void setNoRestricciones(javax.swing.JTextField NoRestricciones) {
        this.txtNoRestricciones = NoRestricciones;
    }

    /**
     * @return the btnContinuar1
     */
    public javax.swing.JButton getBtnContinuar1() {
        return btnContinuar1;
    }

    /**
     * @param btnContinuar1 the btnContinuar1 to set
     */
    public void setBtnContinuar1(javax.swing.JButton btnContinuar1) {
        this.btnContinuar1 = btnContinuar1;
    }

    /**
     * @return the cbMaxMin
     */
    public javax.swing.JComboBox<String> getCbMaxMin() {
        return cbMaxMin;
    }

    /**
     * @param cbMaxMin the cbMaxMin to set
     */
    public void setCbMaxMin(javax.swing.JComboBox<String> cbMaxMin) {
        this.cbMaxMin = cbMaxMin;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @param jLabel3 the jLabel3 to set
     */
    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the txtNoVariablesDesicion
     */
    public javax.swing.JTextField getTxtNoVariablesDesicion() {
        return txtNoVariablesDesicion;
    }

    /**
     * @param txtNoVariablesDesicion the txtNoVariablesDesicion to set
     */
    public void setTxtNoVariablesDesicion(javax.swing.JTextField txtNoVariablesDesicion) {
        this.txtNoVariablesDesicion = txtNoVariablesDesicion;
    }

    /**
     * @return the mostrar_panel
     */
    public boolean getMostrar_panel() {
        return mostrar_panel;
    }

    /**
     * @param mostrar_panel the mostrar_panel to set
     */
    public void setMostrar_panel(boolean mostrar_panel) {
        this.mostrar_panel = mostrar_panel;
    }
}
